#!/bin/bash
set -o nounset
set -o errexit


MIC_CAPTURE=52
MIC_DIGITAL=60

reset_mic_settings()
{
    amixer -c 0 sget Capture | grep -F "Capture $MIC_CAPTURE" > /dev/null && _ex=0 || _ex=$?
    if [[ $_ex -eq 1 ]]; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') resetting mic Capture to $MIC_CAPTURE"
        amixer -c 0 sset Capture $MIC_CAPTURE > /dev/null
    fi
    amixer -c 0 sget 'Mic Boost' | grep -F "Front Left: 0" > /dev/null && _ex=0 || _ex=$?
    if [[ $_ex -eq 1 ]]; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') resetting mic Mic Boost to $MIC_DIGITAL"
        amixer -c 0 sset 'Mic Boost' 0 > /dev/null
    fi
    amixer -c 0 sget 'Internal Mic Boost' | grep -F "Front Left: 1" > /dev/null && _ex=0 || _ex=$?
    if [[ $_ex -eq 1 ]]; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') resetting mic Internal Mic Boost to $MIC_DIGITAL"
        amixer -c 0 sset 'Internal Mic Boost' 1 > /dev/null
    fi
}

reset_mic_settings

exec 3< <(stdbuf -o0 alsactl monitor)
while : ; do
    read -r -t 600 -u 3 line && _ex=0 || _ex=$?
    reset_mic_settings
done
