# [theme]
# file = "~/.config/i3/i3status-rust.theme"

#plain (default)
# theme = "solarized-dark"
# theme = "solarized-light"
# theme = "slick"
# theme = "modern"
# theme = "bad-wolf"
# theme = "gruvbox-light"
# theme = "space-villain"

[theme]
name = "gruvbox-dark"
[theme.overrides]
good_bg = "#59590f"
good_fg = "#ebdbb2"

[icons]
name = "awesome5"

[[block]]
block = "cpu"
interval = 0.7
format = "{utilization}% {barchart}"

[[block]]
block = "custom"
interval = 0.7
command = ''' cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq | sort -r | head -n 1 | awk '{printf("%.1fGhz", $1/1000000)}' '''

[[block]]
block = "custom"
interval = 0.7
command = ''' cat /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon3/temp1_input | awk '{printf("%04.1f℃", $1/1000)}' '''

[[block]]
block = "custom"
interval = 0.7
command = ''' cat /sys/devices/pci0000:00/0000:00:08.1/0000:07:00.0/hwmon/hwmon6/power1_average | awk '{printf("%02.0fW", $1/1000000)}' '''

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}G"
format_swap = "{SUg}G"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
device = "BAT0"

[[block]]
block = "backlight"
device = "amdgpu_bl0"

[[block]]
block = "sound"

[[block]]
block = "custom_dbus"
name = "CurrentKeyboardLayout"
# qdbus i3.status.rs /CurrentKeyboardLayout i3.status.rs.SetStatus us na na

[[block]]
block = "time"
interval = 10
format = "%a %m/%d %R"
