#!/bin/bash
set -o nounset
set -o errexit

GROUP_NUMBER=$(xset -q | grep -E -o "Group 2:\s+on" &>/dev/null && echo "2" || echo "1")
CURRENT_LAYOUT=$(setxkbmap -query | awk '/layout/ {print $2}' | cut -d "," -f "$GROUP_NUMBER")
# qdbus i3.status.rs /CurrentKeyboardLayout i3.status.rs.SetStatus $CURRENT_LAYOUT "" "na"
busctl --user call i3.status.rs /UDKeyboardLayout i3.status.rs SetStatus sss "$CURRENT_LAYOUT" "" ""
