#!/bin/bash

set -o nounset
set -o errexit

source "$(dirname $0)/base"
echo "$DOCKER_RUN_OPTS"
echo "$DOCKER_NODE_MODULES_PATH"
echo "$NODE_MODULES_OUTPUT_DIR"

if [ -e "$NODE_MODULES" ]; then
    rm -rf "$NODE_MODULES" || true
fi

dir_salt=$(echo "$DOCKER_RUN_OPTS" | md5 | rev | cut -c 1-4)
to_path="$HELPERS_DIR/node_from_docker.$dir_salt"
mkdir -p "$to_path"

docker_tmp_container=tmp_node_for_nvim
docker rm -f "$docker_tmp_container" &>/dev/null || true

docker run \
    --name="$docker_tmp_container" \
    $DOCKER_RUN_OPTS \
    -c "true"

docker cp "$docker_tmp_container:$DOCKER_NODE_MODULES_PATH/." "$to_path"
echo "COPIED NODE MODULES TO $to_path"
docker rm -f "$docker_tmp_container" || true

echo "$to_path" > "$NODE_MODULES"
if [ ! -e "$NODE_MODULES_OUTPUT_DIR" ]; then
    sudo ln -sf "$to_path" "$NODE_MODULES_OUTPUT_DIR"
fi
