#!/bin/bash

set -o nounset
set -o errexit

source "$(dirname $0)/base"
source "$(dirname $0)/base_pkg_install"

NODE_VERSION="${NODE_VERSION:-20}"
echo "INSTALLING NVIM JS $NODE_VERSION TOOLS"

nvm which "$NODE_VERSION" || nvm install "$NODE_VERSION"
nvm exec "$NODE_VERSION" npm install -g \
    typescript-language-server \
    typescript-formatter \
    typescript \
    prettier
node_bins=$(dirname $(nvm which "$NODE_VERSION"))
pkgs=(
    "typescript-language-server"
    "tsfmt"
    "node"
    "tsc"
    "tsserver"
    "prettier"
)
for i in "${pkgs[@]}"; do
    _script="#!/bin/bash
set -o nounset
set -o errexit
exec $node_bins/$i \"\$@\""
    printf "$_script" >"$EXECUTABLES_DIR_TO_EXPOSE/$i"
    chmod 0777 "$EXECUTABLES_DIR_TO_EXPOSE/$i"
done
