#!/bin/bash

set -o nounset
set -o errexit

source "$(dirname $0)/base"
source "$(dirname $0)/base_pkg_install"

NODE_VERSION="${NODE_VERSION:-20}"
echo "INSTALLING NVIM JS $NODE_VERSION TOOLS"

nvm which "$NODE_VERSION" || nvm install "$NODE_VERSION"
global_pkgs=(
    "typescript-language-server"
    "typescript-formatter"
    "typescript"
    "prettier-pnp"
)
binaries=(
    "typescript-language-server"
    "tsfmt"
    "node"
    "tsc"
    "tsserver"
    'prettier-pnp --pnp "@ianvs/prettier-plugin-sort-imports" --quiet'
)
exposed_binary_names=(
    "typescript-language-server"
    "tsfmt"
    "node"
    "tsc"
    "tsserver"
    "prettier"
)
nvm exec "$NODE_VERSION" npm install -g "${global_pkgs[@]}"
node_bins=$(dirname $(nvm which "$NODE_VERSION"))

# https://github.com/auvred/prettier-pnp
# node_modules/@ianvs/prettier-plugin-sort-imports/lib/src/index.js

for i in "${!binaries[@]}"; do
    _binary="${binaries[$i]}"
    _name="${exposed_binary_names[$i]}"
    _script="#!/bin/bash
set -o nounset
set -o errexit
exec $node_bins/$_binary \"\$@\""
    printf "$_script" >"$EXECUTABLES_DIR_TO_EXPOSE/$_name"
    chmod 0777 "$EXECUTABLES_DIR_TO_EXPOSE/$_name"
done
