#!/bin/bash

AWS_VAULT_VERSION=$(curl -s https://api.github.com/repos/99designs/aws-vault/releases/latest | jq -r ".name")

sudo curl -L -o /usr/local/bin/aws-vault \
    https://github.com/99designs/aws-vault/releases/download/${AWS_VAULT_VERSION}/aws-vault-linux-amd64
sudo chmod u+x /usr/local/bin/aws-vault
