#!/bin/bash

curl -L -o - \
    https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz \
    | gunzip -c -  >| /tmp/rust-analyzer
sudo mv /tmp/rust-analyzer /usr/local/bin/rust-analyzer
sudo chmod +x /usr/local/bin/rust-analyzer
