confdir /etc/privoxy
# logdir /var/log/privoxy
listen-address 0.0.0.0:3128
# toggle 1

# Forward everything via local Dante, with remote DNS
forward-socks5 / 172.17.0.2:1080 .


# Lock down who can use it (adjust to your LAN)
# permit-access 0.0.0.0/0
# For public exposure, add 'deny-access all' and explicit allows above
