#!/bin/bash

set -o nounset
set -o errexit

source "$(dirname $0)/_base"

while (( "$#" )); do
  case "$1" in
    --executable-name)
      NVIM_EXECUTABLE_NAME=$2
      shift 2
      ;;
      
    --from-docker-image)
      DOCKER_IMAGE=$2
      shift 2
      ;;

    --python-version)
      PYTHON_VERSION=$2
      shift 2
      ;;
    --from-sitepackages-path)
      SITEPACKAGES_PATH=$2
      shift 2
      ;;

    -*|--*=)
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    # *) # preserve positional arguments
    #   PARAMS="$PARAMS $1"
    #   shift
    #   ;;
  esac
done


if [[ ! -z ${DOCKER_IMAGE:-""} ]]; then
    python_version_from_docker_image

    SITEPACKAGES_PATH="$(pyenv root)/sitepackages-copies/$NVIM_EXECUTABLE_NAME"
    mkdir -p $SITEPACKAGES_PATH
    python_copy_docker_image_sitepackages
fi

echo "installing nvim with python $PYTHON_VERSION"
NVIM_BASE_EXECUTABLE="$AUTOGEN_SCRIPTS_DIR/nvim-python-$PYTHON_VERSION"
"$NVIM_CONFIG/install_nvim" \
	--output-executable-path $NVIM_BASE_EXECUTABLE \
	--python-version $PYTHON_VERSION # --force


echo "Create executable nvim with python binary set"
mkdir -p $AUTOGEN_SCRIPTS_DIR
NVIM_PROJECT_EXECUTABLE="$AUTOGEN_SCRIPTS_DIR/$NVIM_EXECUTABLE_NAME"

PYTHONPATH=${PYTHONPATH:=""}
_script="#!/bin/bash
export PYTHONPATH=$PYTHONPATH:$SITEPACKAGES_PATH \\
    && $NVIM_BASE_EXECUTABLE \$@\n"
printf "$_script" > $NVIM_PROJECT_EXECUTABLE

chmod 0777 $NVIM_PROJECT_EXECUTABLE
sudo ln -sf $NVIM_PROJECT_EXECUTABLE /usr/local/bin/$NVIM_EXECUTABLE_NAME 
