[package]
name = "dns-route"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full", "signal"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio-rusqlite = { version = "0.6", features = ["bundled"] }
futures = "0.3"
hickory-proto = "0.25"

[profile.release]
strip = true
lto = true
